[package]
name = "trustchain"
version = "1.0.0"
description = "TrustChain - Decentralized Academic Credential Verification System"
repository = "https://github.com/your-username/trustchain"
keywords = ["blockchain", "education", "credentials", "verification", "internet-computer"]
license = "MIT"

[dependencies]
base = "0.11.1"

[dev-dependencies]
