name: TrustChain CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install DFX
      run: |
        wget https://github.com/dfinity/sdk/releases/download/0.27.0/dfx-0.27.0-x86_64-linux.tar.gz
        tar -xzf dfx-0.27.0-x86_64-linux.tar.gz
        sudo mv dfx /usr/local/bin/
    
    - name: Install dependencies
      run: |
        npm ci
        dfx --version
    
    - name: Install Motoko dependencies
      run: |
        npm install -g ic-mops
        mops install
    
    - name: Start local replica
      run: |
        dfx start --background --clean
      
    - name: Deploy canisters
      run: |
        dfx deploy
        
    - name: Run tests
      run: |
        npm test
        
    - name: Build frontend
      run: |
        npm run build
        
    - name: Stop local replica
      run: |
        dfx stop

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
